FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copy the exact JAR generated by Maven
COPY target/student-management-0.0.1-SNAPSHOT.jar student-management-0.0.1.jar

# Expose the port your Spring Boot app runs on
EXPOSE 8081

# Run the JAR
ENTRYPOINT ["java", "-jar", "student-management-0.0.1.jar"]
